apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workflow-management-system-backend
  annotations:
    github.com/project-slug: Dinuka-Thathsara/workflow-management-system-backend
spec:
  type: other
  lifecycle: unknown
  owner: guests
